<template>
    <div class="contact-us-wrapper">
        <div class="contact-title-wrap">
            <div class="wrapper_1200">
                <div class="contact-top-wrap">
                    <nuxt-link class="home-nav" :to="{ path: '/' }">Home</nuxt-link>
                    <i class="line"></i>
                    <span class="contact-nav">Terms and conditions</span>
                </div>
                <div class="contact-title">
                    Terms & Conditions
                </div>
            </div>
        </div>
        <div class="wrapper_1200 content-wrap">
            <p class="main-title">Overview</p>
            <!-- <p class="main-content">
                The idea for Amba Homes was born out of our own challenges with online shopping. As everyday consumers,
                we were frustrated by products that didn’t match expectations, long wait times, and the lack of personal
                touch that makes shopping enjoyable. We realized there was a gap in the market for an e-commerce
                platform that offered more than just fast delivery or a wide range of products. We wanted to create a
                store that prioritizes:
            </p> -->
            <!-- <ul class="ul-list">
                <li class="item" v-for="(item, index) in ulList" :key="index">
                    <i class="dot"></i>
                    <span class="item-text">{{ item.text }}</span>
                </li>
            </ul> -->
            <p class="mb-6">
                This website (<span class="bg-yellow">www.ambahome.in</span>) ("site" or "website") is operated by
                Amba Homes Pvt. Ltd. Throughout
                this site, the terms "we", "us", and "our" refer to Amba Homes, a company registered in Delhi, India. We
                offer this website, including all information, tools, and services available from this site, to you, the
                user, conditioned upon your acceptance of all terms, conditions, policies, and notices stated here.
            </p>
            <p class="mb-6">This electronic record is generated by a computer system and does not require any physical
                or digital signatures.</p>
            <p class="mb-6">By accessing or using this site and/or making a purchase, you engage with our "Service" and
                agree to be bound by the following terms and conditions ("Terms of Service", "Terms"), including any
                additional terms, conditions, and policies referenced herein or available via hyperlink. These Terms of
                Service apply to all users of the site, including but not limited to browsers, customers, vendors,
                merchants, and/or content contributors.</p>
            <p class="mb-6">Please read these Terms of Service carefully before accessing or using our website. By using
                or accessing any part of the site, you agree to be bound by these Terms. If you do not agree to all the
                terms and conditions of this agreement, you may not access the website or use any of its services.</p>
            <p class="mb-6">Any new features or tools added to the current website shall also be subject to these Terms
                of Service. You can review the most current version of the Terms of Service at any time on this page. We
                reserve the right to update, change, or replace any part of these Terms of Service by posting updates
                and/or changes to our website. We will periodically notify you of any changes to our rules, privacy
                policy, or Terms of Service. Your continued use of or access to the website after any such changes are
                posted will be deemed your acceptance of those changes.</p>
            <p class="main-title">Online Store Terms</p>
            <p class="mb-6">By agreeing to these Terms of Service, you confirm that you are at least the age of majority
                in your state or province of residence, or that you have obtained consent to allow any minor dependents
                to use this site.</p>
            <p class="mb-6">You agree not to use our products or services for any illegal or unauthorized purposes, and
                to comply with all applicable laws, including but not limited to copyright laws, in your jurisdiction.
                You must not transmit any harmful code, such as viruses, worms, or any destructive software.</p>
            <p class="mb-6">To place an order or access our services, you can register an account on the website by
                providing the necessary details. You may delete your account at any time, but we may retain backup
                copies of your registration data as required by applicable laws. You are solely responsible for
                maintaining the confidentiality of your account and password, and for all activities that occur through


                your account. Amba Homes is not liable for any loss or damage resulting from your failure to secure your
                account information. Please ensure your password is kept confidential and secure.</p>
            <p class="mb-6">Any breach of these Terms will result in immediate termination of your access to our
                services.</p>
            <p class="main-title">General Conditions</p>
            <p class="mb-6">We reserve the right to refuse service to anyone at any time for any reason.</p>
            <p class="mb-6">You understand that your content (excluding payment details) may be transferred over
                networks in an unencrypted form and may be adapted to fit the technical requirements of different
                networks or devices. Payment information is always encrypted during transfer.</p>
            <p class="mb-6">You agree not to copy, reproduce, sell, or exploit any part of our service, access to the
                service, or any contact on the website, unless we give you express written permission.</p>
            <p class="main-title">Accuracy, Completeness, and Timeliness of Information</p>
            <p class="mb-6">We are not responsible if the information on this site is inaccurate, incomplete, or
                outdated. The content here is for general information only and should not be the sole basis for making
                decisions. Always consult more reliable or up-to-date sources. Any reliance on the information provided
                is at your own risk.</p>
            <p class="mb-6">This site may include historical information, which is not current and is for reference
                only. We may update or modify the site’s content at any time, but we are not obligated to update any
                information.</p>
            <p class="main-title">Modifications to the Service and Prices</p>
            <p class="mb-6">Prices for our products may change without notice. We also reserve the right to modify or
                discontinue our services (or any part of it) at any time, without notice. We are not liable for any
                changes in prices, service suspensions, or discontinuations.</p>
            <p class="main-title">Accuracy of Billing and Account Information</p>
            <p class="mb-6">We reserve the right to refuse any order you place. We may limit or cancel quantities
                purchased per person, household, or order, including orders made using the same customer account, credit
                card, or billing/shipping address. If we make any changes to or cancel your order, we will try to notify
                you via the contact details you provided.</p>
            <p class="mb-6">We also reserve the right to limit or prohibit orders that appear to be made by dealers,
                resellers, or distributors.</p>
            <p class="mb-6">We reserve the right to limit sales of our products or services to certain people, regions,
                or jurisdictions, and may do so on a case-by-case basis. We also have the right to limit quantities and
                change product descriptions or pricing without notice. Products may be discontinued at any time. Offers
                on the site are void where prohibited.</p>
            <p class="mb-6">We do not guarantee that the quality of any products or services you purchase will meet your
                expectations.</p>
            <p class="main-title">Comments, Feedback, and Other Submissions</p>
            <p class="mb-6">If you send us any comments, suggestions, ideas, or other materials (whether requested or
                not), you agree that we can use them freely, without any obligation to you. This includes editing,
                publishing, or distributing your submissions in any medium.</p>
            <p class="mb-6">We are not required to keep your comments confidential, pay you for them, or respond to
                them.</p>
            <p class="mb-6">We may remove any content we find unlawful, offensive, or otherwise inappropriate, or that
                violates these Terms.</p>
            <p class="mb-6">You agree that your comments will not infringe on any third-party rights, such as copyrights
                or trademarks, and will not contain harmful material like viruses or malware. You also agree not to
                mislead us or others about the origin of your comments. You are responsible for the content and accuracy
                of your comments. We are not liable for any comments made by you or others.</p>
            <p class="main-title">Errors, Inaccuracies, and Omissions</p>
            <p class="mb-6">Occasionally, there may be errors or inaccuracies on our site, such as in product
                descriptions, pricing, promotions, shipping charges, or availability. We reserve the right to correct
                these errors and update or cancel orders if necessary, without prior notice (even after you've placed an
                order).</p>
            <p class="mb-6">We are not obligated to update or clarify any information on our site, except as required by
                law. Just because a date is listed as the last update, it doesn't mean all information has been updated.
            </p>
            <p class="main-title">Prohibited Uses</p>
            <p class="mb-6">You agree not to use our site to host, share, or transmit any content that:</p>
            <p class="mb-6 pl-20" v-for="(item, index) in prohibitedUse" :key="index">{{ item.text }}</p>
            <p class="mb-6">Additionally, you cannot use the site to:</p>
            <p class="mb-6 pl-20" v-for="(item, index) in additionally" :key="index">{{ item.text }}</p>
            <p class="mb-6">We reserve the right to terminate your access if you violate any of these rules.</p>
            <p class="main-title">Disclaimer of Warranties; Limitation of Liability</p>
            <p class="mb-6">Your use of the service is at your own risk. The service and all products are provided "as
                is" and "as available," without any warranties, either expressed or implied. This includes, but is not
                limited to, implied warranties of merchantability, fitness for a particular purpose, or
                non-infringement.</p>
            <p class="mb-6">We, including our employees, contractors, affiliates, and partners, are not liable for any
                direct, indirect, incidental, or consequential damages arising from your use of the service or products.
                This includes, but is not limited to, lost profits, data loss, or damages caused by errors, omissions,
                or the use of any content or product offered through the service.</p>
            <p class="main-title">Indemnification</p>
            <p class="mb-6">You agree to protect and defend us, including our partners, affiliates, employees, and
                agents, from any claims or demands made by a third party due to your breach of these Terms, violation of
                any laws, or infringement of third-party rights. This includes covering any legal fees we may incur.</p>
            <p class="main-title">Severability</p>
            <p class="mb-6">If any part of these Terms is found to be unlawful, void, or unenforceable, it will still be
                enforceable to the maximum extent allowed by law. This won't affect the rest of the Terms, which will
                remain valid.</p>
            <p class="main-title">Termination</p>
            <p class="mb-6">Both parties’ obligations before the termination will still apply after the agreement ends.
                These Terms are effective until either you or we choose to terminate them. You can end these Terms at
                any time by stopping the use of our Services and notifying us.</p>
            <p class="mb-6">If we believe you’ve violated these Terms, we can terminate the agreement without notice.
                You will still be responsible for any amounts due up to the termination date, and we may deny you access
                to our Services.</p>
            <p class="main-title">Force Majeure</p>
            <p class="mb-6">We are not responsible for any delays or failure to provide access to our website, Services,
                or products due to circumstances beyond our control. This includes, but is not limited to, acts of war,
                natural disasters, fires, floods, strikes, government actions, network failures, or cyberattacks.</p>
            <p class="main-title">Entire Agreement</p>
            <p class="mb-6">If we don’t enforce any part of these Terms, it doesn’t mean we’ve waived our right to do so
                in the future. These Terms, along with any other policies posted on the site, form the complete
                agreement between you and us, replacing any previous agreements or discussions.</p>
            <p class="mb-6">If there’s any confusion in interpreting these Terms, it won’t be held against the party
                that wrote them.</p>
            <p class="main-title">Governing Law and Jurisdiction</p>
            <p class="mb-6">These Terms and any related agreements are governed by the laws of India. Any disputes will
                be handled exclusively by the courts in Delhi.</p>
            <p class="main-title">Changes to Terms of Service</p>
            <p class="mb-6">We can update or change these Terms at any time by posting the changes on our website. By
                continuing to use our website or Services, you accept those changes.</p>
        </div>
    </div>
</template>
<script>
export default {
    name: "about",
    auth: false,
    data() {
        return {
            userInfo: {},
            ruleForm: {
                name: '',
                phone: '',
                email: '',
                message: ''
            },
            ulList: [
                {
                    text: 'Quality: Our products are sourced from trusted manufacturers, ensuring you get the best quality at reasonable prices.'
                },
                {
                    text: 'Transparency: What you see is what you get. We believe in being clear about product details, delivery times, and prices — no hidden surprises.'
                },
                {
                    text: 'Customer Satisfaction: We’re here to serve you, not just sell to you. Your satisfaction is our priority, and we’re always ready to assist with any questions or concerns.'
                },
            ],
            prohibitedUse: [
                {
                    text: 'Belongs to someone else without permission.',
                },
                {
                    text: 'Is harmful, defamatory, obscene, or offensive, including content that promotes violence, discrimination, or illegal activities.'
                },
                {
                    text: 'Infringes on any intellectual property rights (like patents or copyrights).'
                },
                {
                    text: 'Misleads others about the origin of a message or shares false information.'
                },
                {
                    text: 'Impersonates someone else or engages in fraudulent activity.'
                },
                {
                    text: 'Threatens national security, public order, or incites violence.'
                },
                {
                    text: ' Contains viruses or harmful software that could damage or disrupt computer resources.'
                },
                {
                    text: 'Violates any law.'
                }
            ],
            additionally: [
                {
                    text: 'Collect or track personal information of others.'
                },
                {
                    text: 'Spam, phish, or scrape content.'
                },
                {
                    text: 'Interfere with the security features of the site or any related websites.'
                },
            ]
        }
    },
    head() {
        return {
            title: ""
        }
    },
    mounted() {
        this.$nextTick(() => {
            document.body.setAttribute("style", "background:#ffffff");
        });
    },
    methods: {
        submit() {
            this.$refs.ruleForm.validate((valid) => {
                if (valid) {
                    this.$message({
                        showClose: true,
                        message: 'you have send a message!',
                        type: 'success'
                    });
                } else {
                    console.log('error submit!!');
                    return false;
                }
            });

        }
    }
}
</script>
<style lang="scss" scoped>
.contact-us-wrapper {
    font-size: 16px;

    .contact-title-wrap {
        height: 205px;
        padding: 40px 0;
        background-color: #f8f8f8;
        margin-bottom: 80px;

        .contact-top-wrap {}

        .home-nav {
            color: #999;
            font-size: 16px;
        }

        .line {
            display: inline-block;
            width: 2px;
            height: 11px;
            background-color: #e5e5e5;
            margin: 0 8px;
        }

        .contact-nav {
            color: #3577f0;
            font-size: 16px;

        }

        .contact-title {
            margin-top: 15px;
            font-size: 34px;
            font-weight: bold;
        }
    }

    .content-wrap {
        color: #777;
    }

    .main-color {
        color: #3577f0;
    }

    .main-title {
        font-size: 20px;
        margin-top: 22px;
        margin-bottom: 16px;
        font-weight: bold;
        color: #000;
    }

    .main-content {
        /* font-size: 18px; */
        margin-bottom: 12px;
    }

}

.ul-list {
    margin-top: 30px;

    .item {
        margin-bottom: 12px;
        display: flex;
    }

    .dot {
        display: inline-block;
        width: 6px;
        height: 6px;
        background-color: #ddd;
        border-radius: 50%;
        margin-right: 8px;
        margin-top: 10px;
    }

    .item-text {
        /* display: inline-block; */
    }
}
</style>
